---
- name: Deploy vulnerable Samba server
  hosts: target_servers
  become: yes

  tasks:
    - name: Install Samba
      apt:
        name: samba
        state: present
        update_cache: yes

    - name: Create public share directory
      file:
        path: /srv/samba/public
        state: directory
        mode: '0777'

    - name: Write insecure smb.conf
      copy:
        dest: /etc/samba/smb.conf
        content: |
          [global]
          workgroup = WORKGROUP
          security = user
          map to guest = Bad User
          server string = Samba Server
          log file = /var/log/samba/log.%m
          max log size = 50
          dns proxy = no

          [Public]
          path = /srv/samba/public
          browsable = yes
          writable = yes
          guest ok = yes
          read only = no

    - name: Restart Samba
      service:
        name: smbd
        state: restarted

