---
- name: Deploy vulnerable WordPress server
  hosts: target_servers
  become: yes

  tasks:
    - name: Install LAMP stack dependencies
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - unzip
        state: present
        update_cache: yes

    - name: Download vulnerable WordPress
      get_url:
        url: https://wordpress.org/wordpress-5.0.0.zip
        dest: /tmp/wordpress.zip

    - name: Unzip WordPress
      unarchive:
        src: /tmp/wordpress.zip
        dest: /var/www/html/
        remote_src: yes

    - name: Set insecure permissions
      file:
        path: /var/www/html/wordpress
        recurse: yes
        mode: "0777"

    - name: Configure MySQL (insecure)
      mysql_db:
        name: wp_db
        state: present

    - name: Create MySQL user (insecure)
      mysql_user:
        name: wp_user
        password: wp_pass
        priv: "wp_db.*:ALL"
        state: present
        host: "%"

    - name: Restart services
      service:
        name: apache2
        state: restarted
